load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "NicegramUI",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//Nicegram/NicegramLib:NicegramLib#shared",
        "//Nicegram/QuickTableViewController:QuickTableViewController#shared",
    	"//submodules/AsyncDisplayKit:AsyncDisplayKit#shared",
        "//submodules/Display:Display#shared",
        "//submodules/TelegramPresentationData:TelegramPresentationData",
        "//submodules/AccountContext:AccountContext",
        "//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
        #"//Nicegram/Zip:Zip"
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ]
)

